In [69]:
# Importing libraries
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.feature_extraction.text import CountVectorizer

In [70]:
# Create sample set of documents
docs = np.array(['Mirabai has won a silver medal in weight lifting in Tokyo olympics 2021',
                 'Sindhu has won a bronze medal in badminton in Tokyo olympics',
                 'Indian hockey team is in top four team in Tokyo olympics 2021 after 40 years'])

In [71]:
vect = CountVectorizer()

In [72]:
# Fit the bag-of-words model
bag_of_words = vect.fit_transform(docs)

In [73]:
# Get unique words / tokens found in all the documents. The unique words / tokens represents the features
print(vect.get_feature_names())

['2021', '40', 'after', 'badminton', 'bronze', 'four', 'has', 'hockey', 'in', 'indian', 'is', 'lifting', 'medal', 'mirabai', 'olympics', 'silver', 'sindhu', 'team', 'tokyo', 'top', 'weight', 'won', 'years']


In [74]:
# Associate the indices with each unique word
print(vect.vocabulary_)

{'mirabai': 13, 'has': 6, 'won': 21, 'silver': 15, 'medal': 12, 'in': 8, 'weight': 20, 'lifting': 11, 'tokyo': 18, 'olympics': 14, '2021': 0, 'sindhu': 16, 'bronze': 4, 'badminton': 3, 'indian': 9, 'hockey': 7, 'team': 17, 'is': 10, 'top': 19, 'four': 5, 'after': 2, '40': 1, 'years': 22}


In [75]:
# Print the numerical feature vector
print(bag_of_words.toarray())

[[1 0 0 0 0 0 1 0 2 0 0 1 1 1 1 1 0 0 1 0 1 1 0]
 [0 0 0 1 1 0 1 0 2 0 0 0 1 0 1 0 1 0 1 0 0 1 0]
 [1 1 1 0 0 1 0 1 2 1 1 0 0 0 1 0 0 2 1 1 0 0 1]]


In [76]:
# Sentimental analysis on "bag of words meets the bag of popcorns" dataset
data = pd.read_csv("C:/Users/user/Downloads/labeledTrainData.tsv", delimiter="\t")
data

id  sentiment                                             review
0       5814_8          1  With all this stuff going down at the moment w...
1       2381_9          1  \The Classic War of the Worlds\" by Timothy Hi...
2       7759_3          0  The film starts with a manager (Nicholas Bell)...
3       3630_4          0  It must be assumed that those who praised this...
4       9495_8          1  Superbly trashy and wondrously unpretentious 8...
...        ...        ...                                                ...
24995   3453_3          0  It seems like more consideration has gone into...
24996   5064_1          0  I don't believe they made this film. Completel...
24997  10905_3          0  Guy is a loser. Can't get girls, needs to buil...
24998  10194_3          0  This 30 minute documentary Buñuel made in the ...
24999   8478_8          1  I saw this movie as a child and it broke my he...

[25000 rows x 3 columns]

In [77]:
# splitting the data into training and testing sets.
def simple_split(data,y,length,split_mark=0.7):
    if split_mark > 0 and split_mark < 1:
        n = int(split_mark * length)
    else:
        n - int(split_mark)
    x_train = data[:n].copy()
    x_test= data[n:].copy()
    y_train= y[:n].copy()
    y_test= y[n:].copy()
    return x_train,x_test,y_train,y_test

In [78]:
# Initializing CountVectorizer
vectorizer = CountVectorizer()

In [79]:
x_train,x_test,y_train,y_test = simple_split(data.review,data.sentiment,len(data))
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(17500,) (7500,) (17500,) (7500,)


In [80]:
print("Samples per class: {}" . format(np.bincount(y_train)))
print("Samples per class: {}" . format(np.bincount(y_test)))

Samples per class: [8761 8739]
Samples per class: [3739 3761]


In [81]:
x_train = vectorizer.fit_transform(x_train)
x_test = vectorizer.transform(x_test)

In [82]:
f_names = vectorizer.get_feature_names()
print("Number of Features : {}". format(len(f_names)))
print("Features 1000 to 1050 : \n{}". format(f_names[1000:1050]))
print("Unique words:\n{}".format(vectorizer.get_feature_names()[:10]))

Number of Features : 65005
Features 1000 to 1050 : 
['abhisheh', 'abhishek', 'abhor', 'abhorrence', 'abhorrent', 'abhors', 'abi', 'abide', 'abides', 'abiding', 'abigail', 'abigil', 'abilities', 'ability', 'abishai', 'abject', 'abjectly', 'abkani', 'able', 'ably', 'abm', 'abner', 'abnormal', 'abnormality', 'abnormally', 'abo', 'aboard', 'abode', 'abodes', 'abolish', 'abolished', 'abolition', 'abolitionism', 'abolitionists', 'abominable', 'abominably', 'abomination', 'abominations', 'abominator', 'abominibal', 'aboooot', 'aborigin', 'aboriginal', 'aboriginals', 'aborigine', 'aborigines', 'aboriginies', 'aborigins', 'aborigone', 'abort']
Unique words:
['00', '000', '0000000000001', '00001', '00015', '000s', '001', '003830', '006', '007']


In [101]:
from itertools import islice
list(islice(vectorizer.vocabulary_.items(), 20))

[('with', 63728),
 ('all', 2250),
 ('this', 57865),
 ('stuff', 55431),
 ('going', 24332),
 ('down', 17279),
 ('at', 4082),
 ('the', 57672),
 ('moment', 37800),
 ('mj', 37605),
 ('ve', 61636),
 ('started', 54657),
 ('listening', 33896),
 ('to', 58358),
 ('his', 27044),
 ('music', 38654),
 ('watching', 62795),
 ('odd', 40456),
 ('documentary', 16869),
 ('here', 26685)]

In [84]:
i = 45000
j=10
words = vectorizer.get_feature_names()[i:i+10]
pd.DataFrame(x_train[j:j+7,i:i+10].todense(),columns = words)

producer  producer9and  producers  produces  producing  product  \
0         0             0          0         0          0        0   
1         0             0          0         0          0        0   
2         0             0          0         0          0        0   
3         0             0          0         0          0        1   
4         0             0          0         0          0        0   
5         0             0          0         0          0        0   
6         0             0          0         0          0        0   

   production  productions  productive  productively  
0           0            0           0             0  
1           0            0           0             0  
2           0            0           0             0  
3           1            0           0             0  
4           1            0           0             0  
5           0            0           0             0  
6           0            0           0             0

In [85]:
scores=cross_val_score(LogisticRegression(max_iter=18000),x_train,y_train,cv=5)
print("Mean cross validation accuracy: {:.2f}".format(np.mean(scores)))

Mean cross validation accuracy: 0.88


In [86]:
logreg = LogisticRegression(max_iter=18000)
logreg.fit(x_train,y_train)
y_pred = logreg.predict(x_test) 
print("Training set score:{:.3f}".format(logreg.score(x_train,y_train)))
print("Testing set score:{:.3f}".format(logreg.score(x_test,y_test)))

Training set score:0.999
Testing set score:0.879


In [87]:
pred_logreg = logreg.predict(x_test)
confusion_logreg = confusion_matrix(y_test,pred_logreg)
print("Confusion matrix:\n{}".format(confusion_logreg))

Confusion matrix:
[[3279  460]
 [ 451 3310]]


In [88]:
# Accuracy of Logistic Regression model
accuracy_logreg = accuracy_score(y_test, pred_logreg).round(2)
print("Accuracy of Logistic Regression:",accuracy_logreg)

Accuracy of Logistic Regression: 0.88


In [89]:
nb=MultinomialNB()
nb.fit(x_train,y_train)
print("Training set score:{:.3f}".format(nb.score(x_train,y_train)))
print("Testing set score:{:.3f}".format(nb.score(x_test,y_test)))

Training set score:0.908
Testing set score:0.845


In [90]:
pred_nb = nb.predict(x_test)
confusion_nb = confusion_matrix(y_test,pred_nb)
print("Confusion matrix:\n{}".format(confusion_nb))

Confusion matrix:
[[3275  464]
 [ 702 3059]]


In [91]:
# Accuracy of Multinomial Naive Bayes model
accuracy_nb = accuracy_score(y_test, pred_nb).round(2)
print("Accuracy of Multinomial Naive Bayes:",accuracy_nb)

Accuracy of Multinomial Naive Bayes: 0.84


In [92]:
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
print("Training set score:{:.3f}".format(rf.score(x_train,y_train)))
print("Testing set score:{:.3f}".format(rf.score(x_test,y_test)))

Training set score:1.000
Testing set score:0.846


In [93]:
pred_rf = rf.predict(x_test)
confusion_rf = confusion_matrix(y_test,pred_rf)
print("Confusion matrix:\n{}".format(confusion_rf))

Confusion matrix:
[[3139  600]
 [ 554 3207]]


In [94]:
# Accuracy of Random Forest Classifier model
accuracy_rf = accuracy_score(y_test, pred_rf).round(2)
print("Accuracy of Random Forest Classifier:",accuracy_rf)

Accuracy of Random Forest Classifier: 0.85
